export const COMMON_CONSTS = {
  CREATE_ACCOUNT: 'Create Account',
  YOUR_NAME: 'Your Name',
  MOBILE_NUMBER: 'Mobile Number',
  PASSWORD: 'Password',
  CONTINUE: 'Continue',
  STAR: '*',
  ENTER_VALID_MOBILE_NUMBER: 'Enter valid Mobile Number',
  ENTER_VALID_PASSWORD: 'Enter valid Password',
  ALREADY_HAVE_AN_ACCOUNT: 'Already have an account?',
  SIGN_IN: 'Sign in',
  CREATE_NEW_ACCOUNT: 'Create new account',
  // eslint-disable-next-line quotes
  DONOT_HAVE_ACCOUNT: "Don't have account?",
  SIGNUP: 'SignUp',
  ALREADY_A_CUSTOMER: 'Already a customer',
  PASSWORD_REGEX: /^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[a-zA-Z]).{8,}$/,
  MOBILE_REGEX: /^(\d{3})[- ]?(\d{3})[- ]?(\d{4})$/,
  OTP: 'Enter OTP sent on mobile number',
  NEED_HELP: 'Need Help?',
  FORGOT_PASSWORD: 'Forgot Password',
  FORGOTPASSWORD: 'ForgotPassword',
  NEW_PASSWORD: 'New password',
  PASSWORD_AGAIN: 'Password again',
  CREATE_NEW_PASSWORD: 'Create new password',
  SAVE_CHANGES_AND_SIGN_IN: 'Save changes and sign in',
  PASSWORD_DID_NOT_MATCH: 'Password did not match',
  AUTHENTICATION_REQUIRED: 'Authentication Required',
  PASSWORD_CONTAIN1:
    'Password must be at least 8 characters long and contain at least',
  PASSWORD_CONTAIN2:
    'one uppercase letter, one, lowercase letter and one digit',
  ENTER_ALL_FIELDS: 'Enter all necessary fields with validation',
  ADD_TO_CART: 'Add To Cart',
  LOGOUT: 'Log out',
  DO_YOU_REALLY_WANT_TO_LOG_OUT: 'Do you really want to Log out?',
  BUY_NOW: 'Buy now',
  HURRY_UP: 'Hurry Up!',
  ITEMS_LEFT: 'Items left:',
  ONLY: 'only',
  PRODUCT_DETAIL: 'Product Detail',
  PLEASE_ENTER_QUANTITY_MANUALLY: 'Please enter quantity manually',
  PLUS: '+',
  MINUS: '-',
  QUANTITY: 'Quantity: ',
  REMOVE_FROM_CART: 'Remove from cart',
};

export const BASE_URL = 'https://bf54-122-160-165-213.in.ngrok.io';
