export const COMMON_CONSTS = {
  CREATE_ACCOUNT: 'Create Account',
  YOUR_NAME: 'Your Name',
  MOBILE_NUMBER: 'Mobile Number',
  PASSWORD: 'Password',
  CONTINUE: 'Continue',
  STAR: '*',
  ENTER_VALID_MOBILE_NUMBER: 'Enter valid Mobile Number',
  ENTER_VALID_PASSWORD: 'Enter valid Password',
  ALREADY_HAVE_AN_ACCOUNT: 'Already have an account?',
  SIGN_IN: 'Sign in',
  CREATE_NEW_ACCOUNT: 'Create new account',
  DONOT_HAVE_ACCOUNT: "Don't have account?",
  SIGNUP: 'SignUp',
  ALREADY_A_CUSTOMER: 'Already a customer',
  PASSWORD_REGEX: /^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[a-zA-Z]).{8,}$/,
  MOBILE_REGEX: /^(\d{3})[- ]?(\d{3})[- ]?(\d{4})$/,
  OTP: 'Enter OTP sent on mobile number',
  NEED_HELP: 'Need Help?',
  FORGOT_PASSWORD: 'Forgot Password',
  FORGOTPASSWORD: 'ForgotPassword',
  NEW_PASSWORD: 'New password',
  PASSWORD_AGAIN: 'Password again',
  CREATE_NEW_PASSWORD: 'Create new password',
  SAVE_CHANGES_AND_SIGN_IN: 'Save changes and sign in',
  PASSWORD_DID_NOT_MATCH: 'Password did not match',
};
